# Python to Linux Web App on Azure
# Build your Python project and deploy it to Azure as a Linux Web App.
# Change python version to one thats appropriate for your application.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  name: "$(MSFT_AGENT_POOL)"

variables:
  - group: az204-vars

  - name: SHORT_SHA
    value: $[ substring( variables['Build.SourceVersion'], 0, 7 ) ]

  - name: webAppName
    value: 'fs204-pythonflaskapp'
 
  - name: environmentName
    value: 'fs204-pythonflaskapp'

  - name: projectRoot
    value: $(System.DefaultWorkingDirectory)

  - name: pythonVersion
    value: '3.11'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    steps:
    - template: pipelines/templates/python-build-checks.yml
      parameters:
        codePath: 'hello_app'
        pythonVersion: $(pythonVersion)

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(SHORT_SHA).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(SHORT_SHA).zip
      displayName: 'Upload package'
      artifact: drop

- stage: Test
  displayName: "Test Stage"
  dependsOn: Build
  condition: succeeded()

  jobs:
  - job: RunTests
    displayName: "Execute unit tests"

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(pythonVersion)

    - script: pip install -r requirements.txt
      displayName: "Install dependencies"

    - script: |
        pytest hello_app \
          --junitxml=test-results.xml \
          --cov=hello_app \
          --cov-report=xml \
          --cov-report=html
      displayName: "Run pytest with coverage"

    - script: coverage report --fail-under=90
      displayName: "Require at least 90% coverage"

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'test-results.xml'
        testResultsFormat: 'JUnit'
        failTaskOnFailedTests: true
      displayName: "Publish test results"

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: 'coverage.xml'
        reportDirectory: 'htmlcov'
      displayName: "Publish code coverage"




- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
            displayName: 'Use Python version'

          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : fs204-pythonflaskapp'
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION_ID)
              appName: $(webAppName)
              appType: 'webAppLinux'
              package: $(Pipeline.Workspace)/drop/$(SHORT_SHA).zip
              startUpCommand: 'startup.txt'
              runtimeStack: 'PYTHON|3.11'
